name: Deploy to Azure App Service

on: # defined to trigger the jobs of the workflow
 
 push:
   branches:
     - feature
jobs:
   deploying-appservice: 
      name: Deploying App Service
      runs-on: self-hosted
      steps:
        - name: Checkout repo
          uses: actions/checkout@v4 # it downloads the repo contents to the runner
         
        # - name: Login to Azure # Azure Login with User Managed Identity
        #   uses: azure/login@v2
        #   with: 
        #     auth-type: Identity
        #     client-id: ${{ secrets.AZURE_CLIENT_ID }}
        #     tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        #     subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

        - name: Login to Azure via Device code
          run: |
            echo "Login to Azure using device code"
            az login --use-device-code
          
        - name: Azure CLI Script
          run: |
            az account show

        - name: Show Resource Groups
          run: |
            az resource list --resource-group ${{ vars.AZURE_RESOURCE_GROUP }} --output table
        
        - name: Creating an app service plan
          run: |
            if ! az appservice plan list --resource-group ${{ vars.AZURE_RESOURCE_GROUP }} | grep -q '"name": "kkasp"'; then
             echo " App service does not exist. Creating it..."
             az appservice plan create -g ${{ vars.AZURE_RESOURCE_GROUP }} -n ${{ vars.AZURE_APP_SERVICE_PLAN }} --is-linux --sku P0V3
            else
              echo "App service plan already exists. Skipping creation..."
            fi
            sleep 5

        - name: Creating a app services
          run: |
            if ! az webapp list --resource-group ${{ vars.AZURE_RESOURCE_GROUP }} | grep -q '"name": "kkphp"'; then
             echo "App service doesnot exists. Creating it.."
             az webapp create --name ${{ vars.AZURE_APP_SERVICE_NAME }} --plan ${{ vars.AZURE_APP_SERVICE_PLAN }} --resource-group ${{ vars.AZURE_RESOURCE_GROUP }} --runtime "php|8.3"
            else
              echo "App service already exists. Skipping Creation..."
            fi
            sleep 5

        - name: Creating a staging Deployment slot
          run: |
            if ! az webapp deployment slot list --name ${{ vars.AZURE_APP_SERVICE_NAME }} --resource-group ${{ vars.AZURE_RESOURCE_GROUP }} | grep -q '"name": "staging"'; then
             echo "Deployment slot "staging" not exists. Creating it.."
             az webapp deployment slot create --name ${{ vars.AZURE_APP_SERVICE_NAME }} --resource-group ${{ vars.AZURE_RESOURCE_GROUP }} --slot ${{ vars.SLOT_NAME }}
            else
              echo "Staging slot exists. Skipping Creation..."
            fi
            sleep 5

        - name: Get App service Publish profile
          run: |
            az webapp deployment list-publishing-profiles --name ${{ vars.AZURE_APP_SERVICE_NAME }} \
              --resource-group ${{ vars.AZURE_RESOURCE_GROUP }} \
              --xml > publish-profile.xml

   
   build-php-app:
     name: build-php-app
     runs-on: self-hosted
     needs: [deploying-appservice] # maintains the dependency of the previous job in current job
     steps:
       - name: Setup PHP
         uses: shivammathur/setup-php@v2
         with:
           php-version: '8.3'

       - name: Upload artifact for deployment job
         uses: actions/upload-artifact@v4
         with:
           name: php-app
           path: .
                  
   
   deploying-artifacts-in-staging-slot:
      name: Deploy Artifacts into staging slot
      needs: [deploying-appservice, build-php-app]
      runs-on: self-hosted
      steps:
        - name: Download artifact from build job
          uses: actions/download-artifact@v4
          with:
            name: php-app

        - name: Deploying Php app to App se
          uses: azure/webapps-deploy@v2
          with:
            app-name: ${{ vars.AZURE_APP_SERVICE_NAME }}
            slot-name: ${{ vars.SLOT_NAME }}
            package: . # represents the current directory

        - name: Get App Service URL of staging slot
          run: |
            echo "App Service URL (Staging Slot): https://${{ vars.AZURE_APP_SERVICE_NAME }}-staging.azurewebsites.net"
          
           
   deploying-artifacts-in-production-slot:
     name: Deploy Artifacts into Production Slot
     runs-on: self-hosted
     needs: [deploying-appservice, build-php-app, deploying-artifacts-in-staging-slot]
     environment:
       name: Prod
     steps:
       - name: Approval Acceptance
         run: echo "Approval done. Ready to deploy artifacts in Production...""
       
       - name: Download artifact from build job
         uses: actions/download-artifact@v4
         with:
           name: php-app

       - name: Deploying Php app to App service production slot
         uses: azure/webapps-deploy@v2
         with:
            app-name: ${{ vars.AZURE_APP_SERVICE_NAME }}
            slot-name: production
            package: . # represents the current directory
        
       - name: Get App Service URL of Production slot
         run: |
            echo "App Service URL (Production Slot): https://${{ vars.AZURE_APP_SERVICE_NAME }}.azurewebsites.net"
          
      

          
       

    
             