name: Deploy to Azure App Service

on:
  push:
    branches:
        - main
        - feature
  workflow_dispatch:

jobs:
    create-appservice:
        name: create-appservice
        runs-on: [self-hosted]
        steps:
          - name: Checkout repo
            uses: actions/checkout@v4
         
          - name: Login to Azure
            uses: azure/login@v2
            with: 
               auth-type: Identity
               tenant-id: ${{ secrets.AZURE_TENANT_ID }}
               subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
               enable-AzPSSession: true
          
          - name: Azure CLI Script
            uses: azure/cli@v2
            with:
              azcliversion: latest
              inlineScript: |
                az account show
            
          - name: Creating an app service plan
            uses: azure/cli@v2
            with:
              azcliversion: latest
              inlineScript: |
                az appservice plan create \
                --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
                --name ${{ secrets.AZURE_APP_SERVICE_PLAN }} \
                --sku F1
                --is-linux

          - name: Creating a php web app service
            uses: azure/cli@v2
            with:
              azcliversion: latest
              inlineScript: |
                az webapp create \
                --name ${{ secrets.AZURE_APP_SERVICE_NAME }} \
                --plan ${{ secrets.AZURE_APP_SERVICE_PLAN }} \
                --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
                --runtime "php|8.3"


          - name: Creating a Deployment slot
            uses: azure/cli@v2
            with:
              azcliversion: latest
              inlineScript: |
                az webapp deployment slot create \
                --name ${{ secrets.AZURE_APP_SERVICE_PLAN }} \
                --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
                --slot ${{ secrets.SLOT_NAME }}

          
          - name: Get App service Publish profile
            run: |
              az webapp deployment list-publishing-profiles \
              --name ${{ secrets.AZURE_APP_SERVICE_NAME }} \
              --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
              --query "[0].publishUrl" -o tsv           
 
    build-php-app:
         name: Deploying Php to app service
         runs-on: [self-hosted]
         needs: create-appservice
         steps:
          - name: Setup PHP
            uses: shivammathur/setup-php@v2
            with:
              php-version: '8.3'

          - name: Install PHP dependencies
            run: |
              curl -sS https://getcomposer.org/installer | php
              php composer.phar install 

    deploy-to-app-service:
       name: Deploy to App Service
       needs: [create-appservice, build-php-app]
       runs-on: self-hosted
       steps:
         - name: Deploying Php app to App service
           uses: azure/webapps-deploy@v2
           with:
             app-name: ${{ secrets.AZURE_APP_SERVICE_NAME }}
             slot-name: ${{ secrets.SLOT_NAME }}
             package: .


    
             
