name: Deploy to Azure App Service

on:
  push:
    branches:
        - main
        - feature
  workflow_dispatch:

permissions:
  id-token: write

jobs:
    create-appservice:
        name: create-appservice
        runs-on: [self-hosted]
        steps:
          - name: Checkout repo
            uses: actions/checkout@v4
         
          - name: Login to Azure
            uses: azure/login@v2
            with:
              creds: ${{ secrets.AZURE_CREDENTIALS }}
            

          - name: Ensure Resource Group exists
            uses: azure/cli@v2.1.0
            with:
              azcliversion: latest
              inlineScript: |
                az group show --name ${{ secrets.AZURE_RESOURCE_GROUP }}

            
          - name: Azure CLI Script
            uses: azure/cli@v2.1.0
            with:
              azcliversion: latest
              inlineScript: |
                az account show
            
          - name: Creating an app service plan
            uses: azure/cli@v2.1.0
            with:
              azcliversion: latest
              inlineScript: |
                az appservice plan create \
                --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
                --name ${{ secrets.AZURE_APP_SERVICE_PLAN }} \
                --location "Central India" \
                --sku Basic
                --is-linux

          - name: Creating a php web app service
            uses: azure/cli@v2.1.0
            with:
              azcliversion: latest
              inlineScript: |
                az webapp create \
                --name ${{ secrets.AZURE_APP_SERVICE_NAME }} \
                --plan ${{ secrets.AZURE_APP_SERVICE_PLAN }} \
                --location "Central India" \
                --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
                --runtime "php|8.3"


          - name: Creating a Deployment slot
            uses: azure/cli@v2.1.0
            with:
              azcliversion: latest
              inlineScript: |
            
                az webapp deployment slot create \
                --name ${{ secrets.AZURE_APP_SERVICE_PLAN }} \
                --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
                --location "Central India" \
                --slot ${{ secrets.SLOT_NAME }}

          
          - name: Get App service Publish profile
            uses: azure/cli@v2.1.0
            with:
              azcliversion: latest
              inlineScript: |
                az webapp deployment list-publishing-profiles \
                --name ${{ secrets.AZURE_APP_SERVICE_NAME }} \
                --location "Central India" \
                --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
                --query "[0].publishUrl" -o tsv           
 
    build-php-app:
        name: Build Php App
        runs-on: [self-hosted]
        needs: create-appservice
        steps:
          - name: Setup PHP
            uses: shivammathur/setup-php@v2
            with:
              php-version: '8.3'

          - name: Install PHP dependencies
            run: |
              curl -sS https://getcomposer.org/installer | php
              php composer.phar install 

          - name: Check if composer.json exists
            id: check_files
            uses: andstor/file-existence-action@2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b
            with:
              files: 'composer.json'


    deploy-to-app-service:
       name: Deploy to App Service
       needs: [create-appservice, build-php-app]
       runs-on: [self-hosted]
       steps:
         - name: Login to Azure
           uses: azure/login@v2
           with:  
             client-id: ${{ secrets.AZURE_CLIENT_ID }}
             tenant-id: ${{ secrets.AZURE_TENANT_ID }}
             client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
             secret-id: ${{ secrets.AZURE_SECRET_ID }}
             subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

         - name: 'Deploy to Azure Web App'
           id: deploy-to-webapp
           uses: azure/webapps-deploy@85270a1854658d167ab239bce43949edb336fa7c
           with:
             app-name: ${{ secrets.AZURE_APP_SERVICE_NAME }}
             package: .
             slot-name: ${{ secrets.SLOT_NAME}}


    
             
