name: deploy to Azure App Service(staging slot)

on: 
  
  workflow_dispatch:

jobs:
   azure-appservice:
      name: Azure App Service
      runs-on: self-hosted
      steps:
        - name: Checkout repo
          uses: actions/checkout@v4
         
        - name: Login to Azure # Azure Login with User Managed Identity
          uses: azure/login@v2
          with: 
            auth-type: Identity
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

        - name: Azure CLI Script
          run: |
              az account show

        - name: Show Resource Groups
          run: |
            az resource list --resource-group ${{ vars.AZURE_RESOURCE_GROUP }} --output table
        
        - name: Creating an app service plan
          run: |
            az appservice plan create -g \
              ${{ vars.AZURE_RESOURCE_GROUP }} \
              -n ${{ vars.AZURE_APP_SERVICE_PLAN }} \
              --is-linux \
              --sku F1 
              sleep 30 

        - name: Creating a php web app service
          run: |
            az webapp create \
              --name ${{ vars.AZURE_APP_SERVICE_NAME }} \
              --plan ${{ vars.AZURE_APP_SERVICE_PLAN }} \
              --resource-group ${{ vars.AZURE_RESOURCE_GROUP }} \
              --runtime "php|8.3"
            sleep 30

        - name: Creating a Deployment slot
          run: |
            az webapp deployment slot create \
              --name ${{ vars.AZURE_APP_SERVICE_NAME }} \
              --resource-group ${{ vars.AZURE_RESOURCE_GROUP }} \
              --slot ${{ vars.SLOT_NAME }}
            sleep 30

        - name: Get App service Publish profile
          run: |
            az webapp deployment list-publishing-profiles \
              --name ${{ vars.AZURE_APP_SERVICE_NAME }} \
              --resource-group ${{ vars.AZURE_RESOURCE_GROUP }} \
              --query "[0].publishUrl" -o tsv   
            sleep 15

        - name: Assigning User Managed Identity to the App Service
          run: |
            az webapp identity assign --name ${{ vars.AZURE_APP_SERVICE_NAME}} \
              --resource-group ${{ vars.AZURE_RESOURCE_GROUP }} 
              --identities ${{ secrets.ASURE_CLIENT_ID }}

   build-php-app:
     name: build-php-app
     runs-on: self-hosted
     needs: [azure-appservice]
     steps:
       - name: Setup PHP
         uses: shivammathur/setup-php@v2
         with:
           php-version: '8.3'

       - name: Install PHP dependencies
         run: |
           curl -sS https://getcomposer.org/installer | php
           php composer.phar install 
           composer --version  

       - name: Upload artifact for deployment job
         uses: actions/upload-artifact@v4
         with:
           name: php-app
           path: .
                  
   deploy-to-app-service:
      name: Deploy to App Service
      needs: [azure-appservice, build-php-app]
      runs-on: self-hosted
      steps:
        - name: Download artifact from build job
          uses: actions/download-artifact@v4
          with:
            name: php-app

        - name: Login to Azure # Azure Login with User Managed Identity
          uses: azure/login@v2
          with: 
            auth-type: Identity
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 
        
        - name: Deploying Php app to App service
          uses: azure/webapps-deploy@v2
          with:
            app-name: ${{ vars.AZURE_APP_SERVICE_NAME }}
            slot-name: ${{ vars.SLOT_NAME }}
            package: . # represents the current directory

    



       

    
             