name: Storage Account Static Website

on: # defined to trigger the jobs of the workflow
 push:
   branches:
     - feature

jobs:
   storage-account:
      name: Deploying Storage Account
      runs-on: self-Hosted
      steps:
        - name: Checkout repo
          uses: actions/checkout@v4 
        
        - name: Azure CLI Script
          run: |
            az account show

        - name: Show the resources under the resource group
          run: |
            az resource list --resource-group ${{ vars.AZURE_RESOURCE_GROUP }} --output table

        - name: Check the Vnet in the Resource Group
          run: |
            az network vnet list --resource-group ${{ vars.AZURE_RESOURCE_GROUP }}

        - name: Checking the Vnet Subnets
          run: |
            az network vnet subnet list --vnet-name ASVM-vnet --resource-group ${{ vars.AZURE_RESOURCE_GROUP }}

        - name: Creating the Storage Account
          run: |
           if ! az storage account list --resource-group "${{ vars.AZURE_RESOURCE_GROUP }}" --query "[?name=='${{ vars.AZURE_STORAGE_ACCOUNT }}']" -o tsv | grep -q .; then
             echo "Storage Account does not exist. Creating it..."
             az storage account create -n ${{ vars.AZURE_STORAGE_ACCOUNT }} -g ${{ vars.AZURE_RESOURCE_GROUP }}  -l "centralindia" --sku Standard_LRS 
           else
             echo "Storage Account already exists. Skipping creation..."
           fi
           sleep 5

        - name: Show the Storage Account
          run: |
            az storage account show --name ${{ vars.AZURE_STORAGE_ACCOUNT }} --resource-group ${{ vars.AZURE_RESOURCE_GROUP }}

   static-website-hosting:
      name: Enable Static Website Hosting
      runs-on: self-Hosted
      needs: [storage-account]
      steps:
        - name: Checking the static Website is enabled
          run: |

            is_enabled=$(az storage blob service-properties show --account-name ${{ vars.AZURE_STORAGE_ACCOUNT }} --query "staticWebsite.enabled" --output tsv)
        
            if [ "$is_enabled" = "true" ]; then
              echo "Static website hosting is already enabled. Skipping this step."
            else
              echo "Static website hosting is not enabled. Enabling now..."
              az storage blob service-properties update --account-name ${{ vars.AZURE_STORAGE_ACCOUNT }} --static-website --index-document index.html
            fi
        
        - name: Verifying Static Website Hosting
          run: |
            az storage blob service-properties show \
            --account-name ${{ vars.AZURE_STORAGE_ACCOUNT }} \
            --query "staticWebsite"
   
  #  storage-container:
  #     name: Creating Storage Container
  #     needs: [storage-account]
  #     runs-on: self-Hosted
  #     steps: 
  #       - name: Deploying Storage Container
  #         run: |
  #           if ! az storage container list --account-name "${{ vars.AZURE_STORAGE_ACCOUNT }}" --query "[?name=='${{ vars.AZURE_STORAGE_CONTAINER }}']" -o tsv | grep -q .; then
  #             echo "Storage Container does not exist. Creating it..."
  #             az storage container create --name "${{ vars.AZURE_STORAGE_CONTAINER }}" --account-name "${{ vars.AZURE_STORAGE_ACCOUNT }}"
  #           else
  #             echo "Storage Container already exists. Skipping creation..."
  #           fi
  #           sleep 5

  #       - name: List out the Container in Storage Account
  #         run: |
  #           az storage container list --account-name ${{ vars.AZURE_STORAGE_ACCOUNT }} --output table
   
   upload-files:
      name: Uploading the Files in Storage Account
      runs-on: self-Hosted
      needs: [storage-account, static-website-hosting]
      steps: 
        - name: Files Uploading in Blob
          run: |
            az storage blob upload-batch --destination ${{ vars.AZURE_STORAGE_CONTAINER }} --source ./${{ vars.FILE_NAME }} --account-name ${{ vars.AZURE_STORAGE_ACCOUNT }}



   verifying-static-website-hosting:
       name: Verifying Static Website Hosting
       runs-on: self-Hosted
       needs: [storage-account, static-website-hosting, upload-files]
       steps:
         - name: Getting Static Website URL
           run: |
             az storage account show \
             --name ${{ vars.AZURE_STORAGE_ACCOUNT }} \
             --query "primaryEndpoints.${{ vars.AZURE_STORAGE_CONTAINER }}" \
             --output tsv

             

        

 