name: Storage Account Static Website

on: # defined to trigger the jobs of the workflow
 push:
   branches:
     - feature

jobs:
   storage-account: # To Create the Storage Account
      name: Deploying Storage Account
      runs-on: self-Hosted
      steps:
        - name: Checkout repo
          uses: actions/checkout@v4 
        
        - name: Azure CLI Script
          run: |
            az account show

        - name: Show the resources under the resource group
          run: |
            az resource list --resource-group ${{ vars.AZURE_RESOURCE_GROUP }} --output table

        - name: Check the Vnet in the Resource Group
          run: |
            az network vnet list --resource-group ${{ vars.AZURE_RESOURCE_GROUP }}

        - name: Checking the Vnet Subnets
          run: |
            az network vnet subnet list --vnet-name ASVM-vnet --resource-group ${{ vars.AZURE_RESOURCE_GROUP }}

        - name: Creating the Storage Account
          run: |
           if ! az storage account list --resource-group "${{ vars.AZURE_RESOURCE_GROUP }}" --query "[?name=='${{ vars.AZURE_STORAGE_ACCOUNT }}']" -o tsv | grep -q .; then
             echo "Storage Account does not exist. Creating it..."
             az storage account create -n ${{ vars.AZURE_STORAGE_ACCOUNT }} -g ${{ vars.AZURE_RESOURCE_GROUP }}  -l "centralindia" --sku Standard_LRS 
           else
             echo "Storage Account already exists. Skipping creation..."
           fi
           sleep 5

        - name: Show the Storage Account
          run: |
            az storage account show --name ${{ vars.AZURE_STORAGE_ACCOUNT }} --resource-group ${{ vars.AZURE_RESOURCE_GROUP }}

   
   storage-container: # To create the Storage Container
      name: Creating Storage Container
      needs: [storage-account]
      runs-on: self-Hosted
      steps: 
        - name: Deploying Storage Container
          run: |
            if ! az storage container list --account-name "${{ vars.AZURE_STORAGE_ACCOUNT }}" --query "[?name=='${{ vars.AZURE_STORAGE_CONTAINER }}']" -o tsv | grep -q .; then
              echo "Storage Container does not exist. Creating it..."
              az storage container create --name "${{ vars.AZURE_STORAGE_CONTAINER }}" --account-name "${{ vars.AZURE_STORAGE_ACCOUNT }}"
            else
              echo "Storage Container already exists. Skipping creation..."
            fi
            sleep 5

        - name: List out the Container in Storage Account
          run: |
            az storage container list --account-name ${{ vars.AZURE_STORAGE_ACCOUNT }} --output table

   
  #  cdn-profile: # To Host the Static Website using CDN Profile
  #      name: CDN profile for Storage Container
  #      runs-on: self-Hosted
  #      needs: [storage-account, storage-container]
  #      steps:
  #        - name: Creating CDN Profile
  #          run: |
  #            az cdn profile create --name ${{ vars.AZURE_CDN_PROFILE }} --resource-group ${{ vars.AZURE_RESOURCE_GROUP }} --location centralindia --sku Standard_Microsoft

  #        - name: Creating CDN Endpoint
  #          run: |
  #            az cdn endpoint create --name ${{ vars.AZURE_CDN_ENDPOINT }} --profile-name ${{ vars.AZURE_CDN_PROFILE }} --resource-group ${{ vars.AZURE_RESOURCE_GROUP }} --origin ${{ vars.AZURE_STORAGE_ACCOUNT }}.blob.core.windows.net
 
  #        - name: Verifying the Endpoint
  #          run: |
  #            az cdn endpoint show --name ${{ vars.AZURE_CDN_ENDPOINT }} --profile-name ${{ vars.AZURE_CDN_PROFILE }} --resource-group ${{ vars.AZURE_RESOURCE_GROUP }}


  #  upload-files: # Uploading Files in Storage Container
  #     name: Uploading the Files in Storage Account
  #     runs-on: self-Hosted
  #     needs: [storage-account, storage-container, cdn-profile]
  #     steps: 
  #       - name: Files Uploading in Blob
  #         run: |
  #           az storage blob upload-batch --container-name ${{ vars.AZURE_STORAGE_CONTAINER }} --source ./${{ vars.FILE_NAME }} --account-name ${{ vars.AZURE_STORAGE_ACCOUNT }}

   
  #  verifying-static-website-hosting:
  #      name: Verifying Static Website Hosting
  #      runs-on: self-Hosted
  #      needs: [storage-account, storage-container, upload-files]
  #      steps:
  #        - name: Getting Static Website URL
  #          run: |
  #            az storage account show \
  #            --name ${{ vars.AZURE_STORAGE_ACCOUNT }} \
  #            --query "primaryEndpoints.${{ vars.AZURE_STORAGE_CONTAINER }}" \
  #            --output tsv

             

        

 